title: Tanner Welsh
email: tannerwelsh@gmail.com
description: >-
  Educator for humans (including self)
baseurl: ""
url: "http://tannerwelsh.com/"
github_repo: "tannerwelsh.github.io"
twitter_username: tannerwelsh
github_username:  tannerwelsh

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  - work
  - education
  - volunteer

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - DESIGN.md
  - README.md
